### ISSUE TITLE
Issue when parsing a list of maps

### ISSUE THREAD

**Issue by alexchicks** [gokmen/hcl-to-json#7]
I receive an error when trying to parse a list of maps as a value. An example would be like the tags attribute below
```
resource "aws_autoscaling_group" "example" {
    name = "example"
    foo = "bar"
 
    tags = [
        {
            key = "tag1"
            value  = "value1"
            propagate_at_launch = true
        },
        {
            key  = "tag2"
            value = "value2"
            propagate_at_launch = true
        },
    ]
}
```

**Comment by gokmen** [comment]
could you attach the error here, thanks.

**Comment by alexchicks** [comment]
Sorry about that

...node_modules/hcl-to-json/lib/index.js:117
          list.push(part.replace(/,$/, ''));
               ^

TypeError: list.push is not a function

**Comment by gokmen** [comment]
Thanks for the report @alexchicks it's fixed and test samples now includes the one you provided as well https://github.com/gokmen/hcl-to-json/blob/master/test/hcl-samples.coffee#L576-L592 npm version updated as well.
